services:
  rasa-server:
    container_name: "rasa_server_compras"
    image: rasa/rasa:3.6.14-full
    working_dir: /app
    ports:
      - "5005:5005"
    volumes:
      - ./rasa_bot:/app
      - ./knowledge_base:/app/knowledge_base
    command: >
      run -m models --enable-api --cors "*" --debug
    networks:
      - chatbot-network

  action-server:
    container_name: "action_server_compras"
    build:
      context: ./rasa_bot/actions
    volumes:
      - ./rasa_bot/actions:/app/actions
      - ./knowledge_base:/app/knowledge_base 
    environment:
      - ERP_API_URL=${ERP_API_URL} 
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5055:5055"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge